export type Category = "FRUITS" | "GAMEPASSES" | "SCROLLS" | "SWORDS" | "MATERIALS" | "LIMITEDS";
export type Rarity = "Common" | "Uncommon" | "Rare" | "Legendary" | "Mythical" | "Limited";
export type Trend = "Stable" | "Rising" | "Falling" | "Underpaid" | "Overpaid";

export interface MockTradeItem {
  id: string;
  name: string;
  slug: string;
  category: Category;
  rarity: Rarity;
  imageUrl: string;
  currentTradingValue: number;
  permanentValue?: number;
  demand: string;
  demandScore: number;
  trend: Trend;
  seoDescription?: string;
  robuxPrice?: number;
  beliPrice?: number;
}

const makeSlug = (name: string) => name.toLowerCase().replace(/[^a-z0-9]+/g, '-');

export const ALL_ITEMS: MockTradeItem[] = [
  {
    id: "real-0",
    name: "West Dragon",
    slug: makeSlug("West Dragon"),
    category: "FRUITS",
    seoDescription: "With its upcoming rework, the West Dragon value has skyrocketed, making it extremely valuable for high-tier trades.",
    rarity: "Mythical" as Rarity,
    imageUrl: "/items/west-dragon.png",
    currentTradingValue: 5130000000,
    permanentValue: 10290000000,
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 5000,
    beliPrice: 15000000
  },
  {
    id: "real-1",
    name: "East Dragon",
    slug: makeSlug("East Dragon"),
    category: "FRUITS",
    seoDescription: "With its upcoming rework, the East Dragon value has skyrocketed, making it extremely valuable for high-tier trades.",
    rarity: "Mythical" as Rarity,
    imageUrl: "/items/east-dragon.png",
    currentTradingValue: 4680000000,
    permanentValue: 10290000000,
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 5000,
    beliPrice: 15000000
  },
  {
    id: "real-2",
    name: "Control",
    slug: makeSlug("Control"),
    category: "FRUITS",
    seoDescription: "The Control fruit is a powerful choice for both PvP and grinding. Check its exact physical and permanent trading value before making offers.",
    rarity: "Mythical" as Rarity,
    imageUrl: "/items/control.webp",
    currentTradingValue: 140000000,
    permanentValue: 8370000000,
    demand: "8/10",
    demandScore: 8,
    trend: "Overpaid" as Trend,
    robuxPrice: 4000,
    beliPrice: 9000000
  },
  {
    id: "real-3",
    name: "Kitsune",
    slug: makeSlug("Kitsune"),
    category: "FRUITS",
    seoDescription: "The Kitsune is currently the most expensive and highest demand mythical beast fruit in the game, dominating the trading values.",
    rarity: "Mythical" as Rarity,
    imageUrl: "/items/kitsune.png",
    currentTradingValue: 600000000,
    permanentValue: 8370000000,
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 4000,
    beliPrice: 8000000
  },
  {
    id: "real-4",
    name: "Yeti",
    slug: makeSlug("Yeti"),
    category: "FRUITS",
    seoDescription: "The Yeti fruit offers incredible mobility and devastating attacks. Check its exact physical and permanent trading value before making offers.",
    rarity: "Mythical" as Rarity,
    imageUrl: "/items/yeti.png",
    currentTradingValue: 140000000,
    permanentValue: 6720000000,
    demand: "8/10",
    demandScore: 8,
    trend: "Stable" as Trend,
    robuxPrice: 3000,
    beliPrice: 5000000
  },
  {
    id: "real-5",
    name: "Gas",
    slug: makeSlug("Gas"),
    category: "FRUITS",
    seoDescription: "The Gas fruit is highly sought after in the trading hub. Check its exact physical and permanent trading value before making offers.",
    rarity: "Mythical" as Rarity,
    imageUrl: "/items/gas.webp",
    currentTradingValue: 60000000,
    permanentValue: 5280000000,
    demand: "8/10",
    demandScore: 8,
    trend: "Stable" as Trend,
    robuxPrice: 2500,
    beliPrice: 3200000
  },
  {
    id: "real-6",
    name: "Tiger",
    slug: makeSlug("Tiger"),
    category: "FRUITS",
    seoDescription: "The Tiger fruit provides excellent elemental immunities for farming. Check its exact physical and permanent trading value before making offers.",
    rarity: "Mythical" as Rarity,
    imageUrl: "/items/tiger.png",
    currentTradingValue: 150000000,
    permanentValue: 6720000000,
    demand: "9/10",
    demandScore: 9,
    trend: "Stable" as Trend,
    robuxPrice: 3000,
    beliPrice: 5000000
  },
  {
    id: "real-7",
    name: "Lightning",
    slug: makeSlug("Lightning"),
    category: "FRUITS",
    seoDescription: "The Lightning fruit is considered a must-have for max level players. Check its exact physical and permanent trading value before making offers.",
    rarity: "Legendary" as Rarity,
    imageUrl: "/items/lightning.png",
    currentTradingValue: 50000000,
    permanentValue: 4200000000,
    demand: "6/10",
    demandScore: 6,
    trend: "Unstable" as Trend,
    robuxPrice: 2100,
    beliPrice: 2100000
  },
  {
    id: "real-8",
    name: "Dough",
    slug: makeSlug("Dough"),
    category: "FRUITS",
    seoDescription: "The Dough fruit features massive area-of-effect damage. Check its exact physical and permanent trading value before making offers.",
    rarity: "Mythical" as Rarity,
    imageUrl: "/items/dough.png",
    currentTradingValue: 30000000,
    permanentValue: 4830000000,
    demand: "9/10",
    demandScore: 9,
    trend: "Stable" as Trend,
    robuxPrice: 2400,
    beliPrice: 2800000
  },
  {
    id: "real-9",
    name: "Pain",
    slug: makeSlug("Pain"),
    category: "FRUITS",
    seoDescription: "The Pain fruit is perfect for bounty hunting and raids. Check its exact physical and permanent trading value before making offers.",
    rarity: "Legendary" as Rarity,
    imageUrl: "/items/pain.png",
    currentTradingValue: 10000000,
    permanentValue: 4410000000,
    demand: "5/10",
    demandScore: 5,
    trend: "Stable" as Trend,
    robuxPrice: 2200,
    beliPrice: 2300000
  },
  {
    id: "real-10",
    name: "T-Rex",
    slug: makeSlug("T-Rex"),
    category: "FRUITS",
    seoDescription: "The T-Rex fruit remains a popular choice among sword mains. Check its exact physical and permanent trading value before making offers.",
    rarity: "Mythical" as Rarity,
    imageUrl: "/items/t-rex.png",
    currentTradingValue: 20000000,
    permanentValue: 4830000000,
    demand: "8/10",
    demandScore: 8,
    trend: "Stable" as Trend,
    robuxPrice: 2350,
    beliPrice: 2700000
  },
  {
    id: "real-11",
    name: "Gravity",
    slug: makeSlug("Gravity"),
    category: "FRUITS",
    seoDescription: "The Gravity fruit is a powerful choice for both PvP and grinding. Check its exact physical and permanent trading value before making offers.",
    rarity: "Mythical" as Rarity,
    imageUrl: "/items/gravity.png",
    currentTradingValue: 10000000,
    permanentValue: 4680000000,
    demand: "5/10",
    demandScore: 5,
    trend: "Stable" as Trend,
    robuxPrice: 2300,
    beliPrice: 2500000
  },
  {
    id: "real-12",
    name: "Mammoth",
    slug: makeSlug("Mammoth"),
    category: "FRUITS",
    seoDescription: "The Mammoth fruit offers incredible mobility and devastating attacks. Check its exact physical and permanent trading value before making offers.",
    rarity: "Mythical" as Rarity,
    imageUrl: "/items/mammoth.png",
    currentTradingValue: 10000000,
    permanentValue: 4830000000,
    demand: "5/10",
    demandScore: 5,
    trend: "Stable" as Trend,
    robuxPrice: 2350,
    beliPrice: 2700000
  },
  {
    id: "real-13",
    name: "Spirit",
    slug: makeSlug("Spirit"),
    category: "FRUITS",
    seoDescription: "The Spirit fruit is highly sought after in the trading hub. Check its exact physical and permanent trading value before making offers.",
    rarity: "Mythical" as Rarity,
    imageUrl: "/items/spirit.png",
    currentTradingValue: 10000000,
    permanentValue: 5280000000,
    demand: "7/10",
    demandScore: 7,
    trend: "Stable" as Trend,
    robuxPrice: 2550,
    beliPrice: 3400000
  },
  {
    id: "real-14",
    name: "Venom",
    slug: makeSlug("Venom"),
    category: "FRUITS",
    seoDescription: "The Venom fruit provides excellent elemental immunities for farming. Check its exact physical and permanent trading value before making offers.",
    rarity: "Mythical" as Rarity,
    imageUrl: "/items/venom.png",
    currentTradingValue: 20000000,
    permanentValue: 4830000000,
    demand: "8/10",
    demandScore: 8,
    trend: "Stable" as Trend,
    robuxPrice: 2450,
    beliPrice: 3000000
  },
  {
    id: "real-15",
    name: "Shadow",
    slug: makeSlug("Shadow"),
    category: "FRUITS",
    seoDescription: "The Shadow fruit is considered a must-have for max level players. Check its exact physical and permanent trading value before making offers.",
    rarity: "Mythical" as Rarity,
    imageUrl: "/items/shadow.png",
    currentTradingValue: 6500000,
    permanentValue: 4830000000,
    demand: "5/10",
    demandScore: 5,
    trend: "Stable" as Trend,
    robuxPrice: 2425,
    beliPrice: 2900000
  },
  {
    id: "real-16",
    name: "Portal",
    slug: makeSlug("Portal"),
    category: "FRUITS",
    seoDescription: "The Portal fruit features massive area-of-effect damage. Check its exact physical and permanent trading value before making offers.",
    rarity: "Legendary" as Rarity,
    imageUrl: "/items/portal.png",
    currentTradingValue: 10000000,
    permanentValue: 3870000000,
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 2000,
    beliPrice: 1900000
  },
  {
    id: "real-17",
    name: "Buddha",
    slug: makeSlug("Buddha"),
    category: "FRUITS",
    seoDescription: "The Buddha fruit is perfect for bounty hunting and raids. Check its exact physical and permanent trading value before making offers.",
    rarity: "Legendary" as Rarity,
    imageUrl: "/items/buddha.png",
    currentTradingValue: 10000000,
    permanentValue: 3090000000,
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 1650,
    beliPrice: 1200000
  },
  {
    id: "real-18",
    name: "Blizzard",
    slug: makeSlug("Blizzard"),
    category: "FRUITS",
    seoDescription: "The Blizzard fruit remains a popular choice among sword mains. Check its exact physical and permanent trading value before making offers.",
    rarity: "Legendary" as Rarity,
    imageUrl: "/items/blizzard.png",
    currentTradingValue: 5000000,
    permanentValue: 4410000000,
    demand: "5/10",
    demandScore: 5,
    trend: "Stable" as Trend,
    robuxPrice: 2250,
    beliPrice: 2400000
  },
  {
    id: "real-19",
    name: "Creation",
    slug: makeSlug("Creation"),
    category: "FRUITS",
    seoDescription: "The Creation fruit is a powerful choice for both PvP and grinding. Check its exact physical and permanent trading value before making offers.",
    rarity: "Legendary" as Rarity,
    imageUrl: "/items/creation.png",
    currentTradingValue: 3000000,
    permanentValue: 3210000000,
    demand: "2/10",
    demandScore: 2,
    trend: "Stable" as Trend,
    robuxPrice: 1750,
    beliPrice: 1400000
  },
  {
    id: "real-20",
    name: "Phoenix",
    slug: makeSlug("Phoenix"),
    category: "FRUITS",
    seoDescription: "The Phoenix fruit offers incredible mobility and devastating attacks. Check its exact physical and permanent trading value before making offers.",
    rarity: "Legendary" as Rarity,
    imageUrl: "/items/phoenix.png",
    currentTradingValue: 2750000,
    permanentValue: 3870000000,
    demand: "3/10",
    demandScore: 3,
    trend: "Stable" as Trend,
    robuxPrice: 2000,
    beliPrice: 1800000
  },
  {
    id: "real-21",
    name: "Sound",
    slug: makeSlug("Sound"),
    category: "FRUITS",
    seoDescription: "The Sound fruit is highly sought after in the trading hub. Check its exact physical and permanent trading value before making offers.",
    rarity: "Legendary" as Rarity,
    imageUrl: "/items/sound.png",
    currentTradingValue: 2500000,
    permanentValue: 3540000000,
    demand: "4/10",
    demandScore: 4,
    trend: "Stable" as Trend,
    robuxPrice: 1900,
    beliPrice: 1700000
  },
  {
    id: "real-22",
    name: "Spider",
    slug: makeSlug("Spider"),
    category: "FRUITS",
    seoDescription: "The Spider fruit provides excellent elemental immunities for farming. Check its exact physical and permanent trading value before making offers.",
    rarity: "Legendary" as Rarity,
    imageUrl: "/items/spider.png",
    currentTradingValue: 1500000,
    permanentValue: 3330000000,
    demand: "2/10",
    demandScore: 2,
    trend: "Stable" as Trend,
    robuxPrice: 1800,
    beliPrice: 1500000
  },
  {
    id: "real-23",
    name: "Love",
    slug: makeSlug("Love"),
    category: "FRUITS",
    seoDescription: "The Love fruit is considered a must-have for max level players. Check its exact physical and permanent trading value before making offers.",
    rarity: "Legendary" as Rarity,
    imageUrl: "/items/love.png",
    currentTradingValue: 1500000,
    permanentValue: 3090000000,
    demand: "3/10",
    demandScore: 3,
    trend: "Stable" as Trend,
    robuxPrice: 1700,
    beliPrice: 1300000
  },
  {
    id: "real-24",
    name: "Magma",
    slug: makeSlug("Magma"),
    category: "FRUITS",
    seoDescription: "The Magma fruit features massive area-of-effect damage. Check its exact physical and permanent trading value before making offers.",
    rarity: "Rare" as Rarity,
    imageUrl: "/items/magma.png",
    currentTradingValue: 1150000,
    permanentValue: 2070000000,
    demand: "5/10",
    demandScore: 5,
    trend: "Overpaid" as Trend,
    robuxPrice: 1300,
    beliPrice: 960000
  },
  {
    id: "real-25",
    name: "Quake",
    slug: makeSlug("Quake"),
    category: "FRUITS",
    seoDescription: "The Quake fruit is perfect for bounty hunting and raids. Check its exact physical and permanent trading value before making offers.",
    rarity: "Legendary" as Rarity,
    imageUrl: "/items/quake.png",
    currentTradingValue: 1000000,
    permanentValue: 2670000000,
    demand: "2/10",
    demandScore: 2,
    trend: "Stable" as Trend,
    robuxPrice: 1500,
    beliPrice: 1000000
  },
  {
    id: "real-26",
    name: "Diamond",
    slug: makeSlug("Diamond"),
    category: "FRUITS",
    seoDescription: "The Diamond fruit remains a popular choice among sword mains. Check its exact physical and permanent trading value before making offers.",
    rarity: "Uncommon" as Rarity,
    imageUrl: "/items/diamond.png",
    currentTradingValue: 1000000,
    permanentValue: 1170000000,
    demand: "2/10",
    demandScore: 2,
    trend: "Stable" as Trend,
    robuxPrice: 1000,
    beliPrice: 600000
  },
  {
    id: "real-27",
    name: "Light",
    slug: makeSlug("Light"),
    category: "FRUITS",
    seoDescription: "The Light fruit is a powerful choice for both PvP and grinding. Check its exact physical and permanent trading value before making offers.",
    rarity: "Rare" as Rarity,
    imageUrl: "/items/light.png",
    currentTradingValue: 800000,
    permanentValue: 1650000000,
    demand: "2/10",
    demandScore: 2,
    trend: "Stable" as Trend,
    robuxPrice: 1100,
    beliPrice: 650000
  },
  {
    id: "real-28",
    name: "Ghost",
    slug: makeSlug("Ghost"),
    category: "FRUITS",
    seoDescription: "The Ghost fruit offers incredible mobility and devastating attacks. Check its exact physical and permanent trading value before making offers.",
    rarity: "Rare" as Rarity,
    imageUrl: "/items/ghost.png",
    currentTradingValue: 800000,
    permanentValue: 1920000000,
    demand: "1/10",
    demandScore: 1,
    trend: "Underpaid" as Trend,
    robuxPrice: 1275,
    beliPrice: 940000
  },
  {
    id: "real-29",
    name: "Eagle",
    slug: makeSlug("Eagle"),
    category: "FRUITS",
    seoDescription: "The Eagle fruit is highly sought after in the trading hub. Check its exact physical and permanent trading value before making offers.",
    rarity: "Uncommon" as Rarity,
    imageUrl: "/items/eagle.png",
    currentTradingValue: 800000,
    permanentValue: 1110000000,
    demand: "2/10",
    demandScore: 2,
    trend: "Stable" as Trend,
    robuxPrice: 975,
    beliPrice: 550000
  },
  {
    id: "real-30",
    name: "Rubber",
    slug: makeSlug("Rubber"),
    category: "FRUITS",
    seoDescription: "The Rubber fruit provides excellent elemental immunities for farming. Check its exact physical and permanent trading value before making offers.",
    rarity: "Rare" as Rarity,
    imageUrl: "/items/rubber.png",
    currentTradingValue: 700000,
    permanentValue: 1770000000,
    demand: "1/10",
    demandScore: 1,
    trend: "Stable" as Trend,
    robuxPrice: 1200,
    beliPrice: 750000
  },
  {
    id: "real-31",
    name: "Ice",
    slug: makeSlug("Ice"),
    category: "FRUITS",
    seoDescription: "The Ice fruit is considered a must-have for max level players. Check its exact physical and permanent trading value before making offers.",
    rarity: "Uncommon" as Rarity,
    imageUrl: "/items/ice.png",
    currentTradingValue: 550000,
    permanentValue: 630000000,
    demand: "2/10",
    demandScore: 2,
    trend: "Stable" as Trend,
    robuxPrice: 750,
    beliPrice: 350000
  },
  {
    id: "real-32",
    name: "Sand",
    slug: makeSlug("Sand"),
    category: "FRUITS",
    seoDescription: "The Sand fruit features massive area-of-effect damage. Check its exact physical and permanent trading value before making offers.",
    rarity: "Uncommon" as Rarity,
    imageUrl: "/items/sand.png",
    currentTradingValue: 420000,
    permanentValue: 840000000,
    demand: "1/10",
    demandScore: 1,
    trend: "Stable" as Trend,
    robuxPrice: 850,
    beliPrice: 420000
  },
  {
    id: "real-33",
    name: "Dark",
    slug: makeSlug("Dark"),
    category: "FRUITS",
    seoDescription: "The Dark fruit is perfect for bounty hunting and raids. Check its exact physical and permanent trading value before making offers.",
    rarity: "Uncommon" as Rarity,
    imageUrl: "/items/dark.png",
    currentTradingValue: 400000,
    permanentValue: 1050000000,
    demand: "1/10",
    demandScore: 1,
    trend: "Stable" as Trend,
    robuxPrice: 950,
    beliPrice: 500000
  },
  {
    id: "real-34",
    name: "Flame",
    slug: makeSlug("Flame"),
    category: "FRUITS",
    seoDescription: "The Flame fruit remains a popular choice among sword mains. Check its exact physical and permanent trading value before making offers.",
    rarity: "Uncommon" as Rarity,
    imageUrl: "/items/flame.png",
    currentTradingValue: 250000,
    permanentValue: 450000000,
    demand: "1/10",
    demandScore: 1,
    trend: "Stable" as Trend,
    robuxPrice: 550,
    beliPrice: 250000
  },
  {
    id: "real-35",
    name: "Spike",
    slug: makeSlug("Spike"),
    category: "FRUITS",
    seoDescription: "The Spike fruit is a powerful choice for both PvP and grinding. Check its exact physical and permanent trading value before making offers.",
    rarity: "Common" as Rarity,
    imageUrl: "/items/spike.png",
    currentTradingValue: 180000,
    permanentValue: 140000000,
    demand: "1/10",
    demandScore: 1,
    trend: "Stable" as Trend,
    robuxPrice: 380,
    beliPrice: 180000
  },
  {
    id: "real-36",
    name: "Smoke",
    slug: makeSlug("Smoke"),
    category: "FRUITS",
    seoDescription: "The Smoke fruit offers incredible mobility and devastating attacks. Check its exact physical and permanent trading value before making offers.",
    rarity: "Common" as Rarity,
    imageUrl: "/items/smoke.png",
    currentTradingValue: 100000,
    permanentValue: 120000000,
    demand: "1/10",
    demandScore: 1,
    trend: "Stable" as Trend,
    robuxPrice: 250,
    beliPrice: 100000
  },
  {
    id: "real-37",
    name: "Bomb",
    slug: makeSlug("Bomb"),
    category: "FRUITS",
    seoDescription: "The Bomb fruit is highly sought after in the trading hub. Check its exact physical and permanent trading value before making offers.",
    rarity: "Common" as Rarity,
    imageUrl: "/items/bomb.png",
    currentTradingValue: 80000,
    permanentValue: 90000000,
    demand: "1/10",
    demandScore: 1,
    trend: "Stable" as Trend,
    robuxPrice: 220,
    beliPrice: 80000
  },
  {
    id: "real-38",
    name: "Spring",
    slug: makeSlug("Spring"),
    category: "FRUITS",
    seoDescription: "The Spring fruit provides excellent elemental immunities for farming. Check its exact physical and permanent trading value before making offers.",
    rarity: "Common" as Rarity,
    imageUrl: "/items/spring.png",
    currentTradingValue: 60000,
    permanentValue: 60000000,
    demand: "1/10",
    demandScore: 1,
    trend: "Stable" as Trend,
    robuxPrice: 180,
    beliPrice: 60000
  },
  {
    id: "real-39",
    name: "Blade",
    slug: makeSlug("Blade"),
    category: "SWORDS",
    seoDescription: "The Blade is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Common" as Rarity,
    imageUrl: "/items/blade.png",
    currentTradingValue: 50000,
    permanentValue: 20000000,
    demand: "1/10",
    demandScore: 1,
    trend: "Stable" as Trend,
    robuxPrice: 100,
    beliPrice: 30000
  },
  {
    id: "real-40",
    name: "Spin",
    slug: makeSlug("Spin"),
    category: "FRUITS",
    seoDescription: "The Spin fruit is considered a must-have for max level players. Check its exact physical and permanent trading value before making offers.",
    rarity: "Common" as Rarity,
    imageUrl: "/items/spin.png",
    currentTradingValue: 7500,
    permanentValue: 15000000,
    demand: "1/10",
    demandScore: 1,
    trend: "Stable" as Trend,
    robuxPrice: 75,
    beliPrice: 7500
  },
  {
    id: "real-41",
    name: "Rocket",
    slug: makeSlug("Rocket"),
    category: "FRUITS",
    seoDescription: "The Rocket fruit features massive area-of-effect damage. Check its exact physical and permanent trading value before making offers.",
    rarity: "Common" as Rarity,
    imageUrl: "/items/rocket.png",
    currentTradingValue: 5000,
    permanentValue: 10000000,
    demand: "1/10",
    demandScore: 1,
    trend: "Stable" as Trend,
    robuxPrice: 50,
    beliPrice: 5000
  },
  {
    id: "real-42",
    name: "Permanent Dragon Token",
    slug: makeSlug("Permanent Dragon Token"),
    category: "LIMITEDS",
    seoDescription: "The Permanent Dragon Token is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/permanent-dragon-token.png",
    currentTradingValue: 0,
    
    demand: "6/10",
    demandScore: 6,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-43",
    name: "Fiend Yeti",
    slug: makeSlug("Fiend Yeti"),
    category: "LIMITEDS",
    seoDescription: "The Fiend Yeti is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/fiend-yeti.webp",
    currentTradingValue: 1110000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-44",
    name: "Galaxy Empyrean Kitsune",
    slug: makeSlug("Galaxy Empyrean Kitsune"),
    category: "LIMITEDS",
    seoDescription: "The Galaxy Empyrean Kitsune is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/galaxy-empyrean-kitsune.webp",
    currentTradingValue: 14580000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-45",
    name: "Ember West Dragon",
    slug: makeSlug("Ember West Dragon"),
    category: "LIMITEDS",
    seoDescription: "The Ember West Dragon is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/ember-west-dragon.webp",
    currentTradingValue: 8520000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-46",
    name: "Crimson Kitsune",
    slug: makeSlug("Crimson Kitsune"),
    category: "LIMITEDS",
    seoDescription: "The Crimson Kitsune is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/crimson-kitsune.webp",
    currentTradingValue: 11790000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 2000,
    beliPrice: 0
  },
  {
    id: "real-47",
    name: "Meme-Meme",
    slug: makeSlug("Meme-Meme"),
    category: "LIMITEDS",
    seoDescription: "The Meme-Meme is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/meme-meme.webp",
    currentTradingValue: 7290000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-48",
    name: "Divine Portal",
    slug: makeSlug("Divine Portal"),
    category: "LIMITEDS",
    seoDescription: "The Divine Portal is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/divine-portal.webp",
    currentTradingValue: 2040000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-49",
    name: "Purple Lightning",
    slug: makeSlug("Purple Lightning"),
    category: "LIMITEDS",
    seoDescription: "The Purple Lightning is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/purple-lightning.png",
    currentTradingValue: 7170000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-50",
    name: "Parrot",
    slug: makeSlug("Parrot"),
    category: "LIMITEDS",
    seoDescription: "The Parrot is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/parrot.png",
    currentTradingValue: 0,
    
    demand: "1/10",
    demandScore: 1,
    trend: "Stable" as Trend,
    robuxPrice: 499,
    beliPrice: 0
  },
  {
    id: "real-51",
    name: "Red Lightning",
    slug: makeSlug("Red Lightning"),
    category: "LIMITEDS",
    seoDescription: "The Red Lightning is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/red-lightning.png",
    currentTradingValue: 2310000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-52",
    name: "Yellow Lightning",
    slug: makeSlug("Yellow Lightning"),
    category: "LIMITEDS",
    seoDescription: "The Yellow Lightning is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/yellow-lightning.png",
    currentTradingValue: 2340000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-53",
    name: "Green Lightning",
    slug: makeSlug("Green Lightning"),
    category: "LIMITEDS",
    seoDescription: "The Green Lightning is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/green-lightning.png",
    currentTradingValue: 720000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-54",
    name: "Werewolf",
    slug: makeSlug("Werewolf"),
    category: "LIMITEDS",
    seoDescription: "The Werewolf is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/werewolf.png",
    currentTradingValue: 1200000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-55",
    name: "Rose Quartz Diamond",
    slug: makeSlug("Rose Quartz Diamond"),
    category: "LIMITEDS",
    seoDescription: "The Rose Quartz Diamond is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/rose-quartz-diamond.webp",
    currentTradingValue: 280000000,
    
    demand: "7/10",
    demandScore: 7,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-56",
    name: "Emerald Diamond",
    slug: makeSlug("Emerald Diamond"),
    category: "LIMITEDS",
    seoDescription: "The Emerald Diamond is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/emerald-diamond.webp",
    currentTradingValue: 220000000,
    
    demand: "6/10",
    demandScore: 6,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-57",
    name: "Topaz Diamond",
    slug: makeSlug("Topaz Diamond"),
    category: "LIMITEDS",
    seoDescription: "The Topaz Diamond is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/topaz-diamond.webp",
    currentTradingValue: 220000000,
    
    demand: "6/10",
    demandScore: 6,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-58",
    name: "Ruby Diamond",
    slug: makeSlug("Ruby Diamond"),
    category: "LIMITEDS",
    seoDescription: "The Ruby Diamond is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/ruby-diamond.webp",
    currentTradingValue: 170000000,
    
    demand: "6/10",
    demandScore: 6,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-59",
    name: "Dragon Token",
    slug: makeSlug("Dragon Token"),
    category: "LIMITEDS",
    seoDescription: "The Dragon Token is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/dragon-token.png",
    currentTradingValue: 0,
    
    demand: "4/10",
    demandScore: 4,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-60",
    name: "Eclipse",
    slug: makeSlug("Eclipse"),
    category: "LIMITEDS",
    seoDescription: "The Eclipse is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/eclipse.png",
    currentTradingValue: 0,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-61",
    name: "Super Spirit Pain",
    slug: makeSlug("Super Spirit Pain"),
    category: "LIMITEDS",
    seoDescription: "The Super Spirit Pain is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/super-spirit-pain.png",
    currentTradingValue: 2280000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-62",
    name: "Torment Pain",
    slug: makeSlug("Torment Pain"),
    category: "LIMITEDS",
    seoDescription: "The Torment Pain is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/torment-pain.png",
    currentTradingValue: 140000000,
    
    demand: "7/10",
    demandScore: 7,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-63",
    name: "Sadness Pain",
    slug: makeSlug("Sadness Pain"),
    category: "LIMITEDS",
    seoDescription: "The Sadness Pain is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/sadness-pain.png",
    currentTradingValue: 720000000,
    
    demand: "9/10",
    demandScore: 9,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-64",
    name: "Frustration Pain",
    slug: makeSlug("Frustration Pain"),
    category: "LIMITEDS",
    seoDescription: "The Frustration Pain is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/frustration-pain.png",
    currentTradingValue: 510000000,
    
    demand: "9/10",
    demandScore: 9,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-65",
    name: "Celestial Pain",
    slug: makeSlug("Celestial Pain"),
    category: "LIMITEDS",
    seoDescription: "The Celestial Pain is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/celestial-pain.png",
    currentTradingValue: 720000000,
    
    demand: "9/10",
    demandScore: 9,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-66",
    name: "Eagle Requiem",
    slug: makeSlug("Eagle Requiem"),
    category: "LIMITEDS",
    seoDescription: "The Eagle Requiem is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/eagle-requiem.png",
    currentTradingValue: 160000000,
    
    demand: "4/10",
    demandScore: 4,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-67",
    name: "Eagle Glacier",
    slug: makeSlug("Eagle Glacier"),
    category: "LIMITEDS",
    seoDescription: "The Eagle Glacier is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/eagle-glacier.png",
    currentTradingValue: 20000000,
    
    demand: "3/10",
    demandScore: 3,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-68",
    name: "Eagle Matrix",
    slug: makeSlug("Eagle Matrix"),
    category: "LIMITEDS",
    seoDescription: "The Eagle Matrix is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/eagle-matrix.png",
    currentTradingValue: 250000000,
    
    demand: "7/10",
    demandScore: 7,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-69",
    name: "Celebration Bomb",
    slug: makeSlug("Celebration Bomb"),
    category: "LIMITEDS",
    seoDescription: "The Celebration Bomb is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/celebration-bomb.png",
    currentTradingValue: 10000000,
    
    demand: "3/10",
    demandScore: 3,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-70",
    name: "Azura Bomb",
    slug: makeSlug("Azura Bomb"),
    category: "LIMITEDS",
    seoDescription: "The Azura Bomb is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/azura-bomb.png",
    currentTradingValue: 450000000,
    
    demand: "6/10",
    demandScore: 6,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-71",
    name: "Thermite Bomb",
    slug: makeSlug("Thermite Bomb"),
    category: "LIMITEDS",
    seoDescription: "The Thermite Bomb is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/thermite-bomb.png",
    currentTradingValue: 450000000,
    
    demand: "6/10",
    demandScore: 6,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-72",
    name: "Nuclear Bomb",
    slug: makeSlug("Nuclear Bomb"),
    category: "LIMITEDS",
    seoDescription: "The Nuclear Bomb is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/nuclear-bomb.png",
    currentTradingValue: 450000000,
    
    demand: "6/10",
    demandScore: 6,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-73",
    name: "Orange Portal",
    slug: makeSlug("Orange Portal"),
    category: "LIMITEDS",
    seoDescription: "The Orange Portal is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Limited" as Rarity,
    imageUrl: "/items/orange-portal.png",
    currentTradingValue: 0,
    
    demand: "5/10",
    demandScore: 5,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-74",
    name: "Fruit Notifier",
    slug: makeSlug("Fruit Notifier"),
    category: "GAMEPASSES",
    seoDescription: "The Fruit Notifier gamepass is a permanent account upgrade that carries incredibly high trading value compared to physical fruits.",
    rarity: "Gamepass" as Rarity,
    imageUrl: "/items/fruit-notifier.png",
    currentTradingValue: 7170000000,
    
    demand: "9/10",
    demandScore: 9,
    trend: "Stable" as Trend,
    robuxPrice: 2700,
    beliPrice: 0
  },
  {
    id: "real-75",
    name: "Dark Blade",
    slug: makeSlug("Dark Blade"),
    category: "SWORDS",
    seoDescription: "The Dark Blade is a rare item that commands specific trading value in the current Blox Fruits market.",
    rarity: "Gamepass" as Rarity,
    imageUrl: "/items/dark-blade.png",
    currentTradingValue: 1770000000,
    
    demand: "9/10",
    demandScore: 9,
    trend: "Stable" as Trend,
    robuxPrice: 1200,
    beliPrice: 0
  },
  {
    id: "real-76",
    name: "Mythical Scrolls",
    slug: makeSlug("Mythical Scrolls"),
    category: "SCROLLS",
    seoDescription: "The Mythical Scrolls is used for weapon enchantments, making it a niche but highly valuable item in the Blox Fruits economy.",
    rarity: "Gamepass" as Rarity,
    imageUrl: "/items/mythical-scrolls.png",
    currentTradingValue: 2670000000,
    
    demand: "4/10",
    demandScore: 4,
    trend: "Stable" as Trend,
    robuxPrice: 1500,
    beliPrice: 0
  },
  {
    id: "real-77",
    name: "Legendary Scrolls",
    slug: makeSlug("Legendary Scrolls"),
    category: "SCROLLS",
    seoDescription: "The Legendary Scrolls is used for weapon enchantments, making it a niche but highly valuable item in the Blox Fruits economy.",
    rarity: "Gamepass" as Rarity,
    imageUrl: "/items/legendary-scrolls.png",
    currentTradingValue: 810000000,
    
    demand: "3/10",
    demandScore: 3,
    trend: "Stable" as Trend,
    robuxPrice: 800,
    beliPrice: 0
  },
  {
    id: "real-78",
    name: "+1 Fruit Storage",
    slug: makeSlug("+1 Fruit Storage"),
    category: "GAMEPASSES",
    seoDescription: "The +1 Fruit Storage gamepass is a permanent account upgrade that carries incredibly high trading value compared to physical fruits.",
    rarity: "Gamepass" as Rarity,
    imageUrl: "/items/-1-fruit-storage.png",
    currentTradingValue: 450000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 400,
    beliPrice: 0
  },
  {
    id: "real-79",
    name: "2x Mastery",
    slug: makeSlug("2x Mastery"),
    category: "GAMEPASSES",
    seoDescription: "The 2x Mastery gamepass is a permanent account upgrade that carries incredibly high trading value compared to physical fruits.",
    rarity: "Gamepass" as Rarity,
    imageUrl: "/items/2x-mastery.png",
    currentTradingValue: 450000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 450,
    beliPrice: 0
  },
  {
    id: "real-80",
    name: "2x Money",
    slug: makeSlug("2x Money"),
    category: "GAMEPASSES",
    seoDescription: "The 2x Money gamepass is a permanent account upgrade that carries incredibly high trading value compared to physical fruits.",
    rarity: "Gamepass" as Rarity,
    imageUrl: "/items/2x-money.png",
    currentTradingValue: 450000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 450,
    beliPrice: 0
  },
  {
    id: "real-81",
    name: "2x Boss Drops",
    slug: makeSlug("2x Boss Drops"),
    category: "GAMEPASSES",
    seoDescription: "The 2x Boss Drops gamepass is a permanent account upgrade that carries incredibly high trading value compared to physical fruits.",
    rarity: "Gamepass" as Rarity,
    imageUrl: "/items/2x-boss-drops.png",
    currentTradingValue: 300000000,
    
    demand: "8/10",
    demandScore: 8,
    trend: "Overpaid" as Trend,
    robuxPrice: 350,
    beliPrice: 0
  },
  {
    id: "real-82",
    name: "Fast Boats",
    slug: makeSlug("Fast Boats"),
    category: "GAMEPASSES",
    seoDescription: "The Fast Boats gamepass is a permanent account upgrade that carries incredibly high trading value compared to physical fruits.",
    rarity: "Gamepass" as Rarity,
    imageUrl: "/items/fast-boats.png",
    currentTradingValue: 300000000,
    
    demand: "9/10",
    demandScore: 9,
    trend: "Overpaid" as Trend,
    robuxPrice: 350,
    beliPrice: 0
  },
];
