export type Category = "FRUITS" | "GAMEPASSES" | "SCROLLS" | "SWORDS" | "MATERIALS" | "LIMITEDS";
export type Rarity = "Common" | "Uncommon" | "Rare" | "Legendary" | "Mythical" | "Limited";
export type Trend = "Stable" | "Rising" | "Falling" | "Underpaid" | "Overpaid";

export interface MockTradeItem {
  id: string;
  name: string;
  slug: string;
  category: Category;
  rarity: Rarity;
  imageUrl: string;
  currentTradingValue: number;
  permanentValue?: number;
  demand: string;
  demandScore: number;
  trend: Trend;
  robuxPrice?: number;
  beliPrice?: number;
}

const makeSlug = (name: string) => name.toLowerCase().replace(/[^a-z0-9]+/g, '-');

export const ALL_ITEMS: MockTradeItem[] = [
  {
    id: "real-0",
    name: "West Dragon",
    slug: makeSlug("West Dragon"),
    category: "FRUITS",
    rarity: "Mythical" as Rarity,
    imageUrl: "https://i.postimg.cc/7LfBxxs8/West-Dragon.png",
    currentTradingValue: 5130000000,
    permanentValue: 10290000000,
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 5000,
    beliPrice: 15000000
  },
  {
    id: "real-1",
    name: "East Dragon",
    slug: makeSlug("East Dragon"),
    category: "FRUITS",
    rarity: "Mythical" as Rarity,
    imageUrl: "https://i.postimg.cc/gkzHzzjS/East-Dragon.png",
    currentTradingValue: 4680000000,
    permanentValue: 10290000000,
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 5000,
    beliPrice: 15000000
  },
  {
    id: "real-2",
    name: "Control",
    slug: makeSlug("Control"),
    category: "FRUITS",
    rarity: "Mythical" as Rarity,
    imageUrl: "https://i.postimg.cc/t48L8bFV/latest-cb-20251223165924.webp",
    currentTradingValue: 140000000,
    permanentValue: 8370000000,
    demand: "8/10",
    demandScore: 8,
    trend: "Overpaid" as Trend,
    robuxPrice: 4000,
    beliPrice: 9000000
  },
  {
    id: "real-3",
    name: "Kitsune",
    slug: makeSlug("Kitsune"),
    category: "FRUITS",
    rarity: "Mythical" as Rarity,
    imageUrl: "https://i.postimg.cc/CLxbycr9/Kitsune.png",
    currentTradingValue: 600000000,
    permanentValue: 8370000000,
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 4000,
    beliPrice: 8000000
  },
  {
    id: "real-4",
    name: "Yeti",
    slug: makeSlug("Yeti"),
    category: "FRUITS",
    rarity: "Mythical" as Rarity,
    imageUrl: "https://i.postimg.cc/mrJmk0Jc/Yeti.png",
    currentTradingValue: 140000000,
    permanentValue: 6720000000,
    demand: "8/10",
    demandScore: 8,
    trend: "Stable" as Trend,
    robuxPrice: 3000,
    beliPrice: 5000000
  },
  {
    id: "real-5",
    name: "Gas",
    slug: makeSlug("Gas"),
    category: "FRUITS",
    rarity: "Mythical" as Rarity,
    imageUrl: "https://i.postimg.cc/XNCpc4fS/1000-cb-20241223162315.webp",
    currentTradingValue: 60000000,
    permanentValue: 5280000000,
    demand: "8/10",
    demandScore: 8,
    trend: "Stable" as Trend,
    robuxPrice: 2500,
    beliPrice: 3200000
  },
  {
    id: "real-6",
    name: "Tiger",
    slug: makeSlug("Tiger"),
    category: "FRUITS",
    rarity: "Mythical" as Rarity,
    imageUrl: "https://i.postimg.cc/vBDS3KNp/download.png",
    currentTradingValue: 150000000,
    permanentValue: 6720000000,
    demand: "9/10",
    demandScore: 9,
    trend: "Stable" as Trend,
    robuxPrice: 3000,
    beliPrice: 5000000
  },
  {
    id: "real-7",
    name: "Lightning",
    slug: makeSlug("Lightning"),
    category: "FRUITS",
    rarity: "Legendary" as Rarity,
    imageUrl: "https://i.postimg.cc/MHTHLFZD/Rumble.png",
    currentTradingValue: 50000000,
    permanentValue: 4200000000,
    demand: "6/10",
    demandScore: 6,
    trend: "Unstable" as Trend,
    robuxPrice: 2100,
    beliPrice: 2100000
  },
  {
    id: "real-8",
    name: "Dough",
    slug: makeSlug("Dough"),
    category: "FRUITS",
    rarity: "Mythical" as Rarity,
    imageUrl: "https://i.postimg.cc/wxckYyqR/Dough.png",
    currentTradingValue: 30000000,
    permanentValue: 4830000000,
    demand: "9/10",
    demandScore: 9,
    trend: "Stable" as Trend,
    robuxPrice: 2400,
    beliPrice: 2800000
  },
  {
    id: "real-9",
    name: "Pain",
    slug: makeSlug("Pain"),
    category: "FRUITS",
    rarity: "Legendary" as Rarity,
    imageUrl: "https://i.postimg.cc/mk21srj7/Pain.png",
    currentTradingValue: 10000000,
    permanentValue: 4410000000,
    demand: "5/10",
    demandScore: 5,
    trend: "Stable" as Trend,
    robuxPrice: 2200,
    beliPrice: 2300000
  },
  {
    id: "real-10",
    name: "T-Rex",
    slug: makeSlug("T-Rex"),
    category: "FRUITS",
    rarity: "Mythical" as Rarity,
    imageUrl: "https://i.postimg.cc/zGDtcwTf/T-Rex.png",
    currentTradingValue: 20000000,
    permanentValue: 4830000000,
    demand: "8/10",
    demandScore: 8,
    trend: "Stable" as Trend,
    robuxPrice: 2350,
    beliPrice: 2700000
  },
  {
    id: "real-11",
    name: "Gravity",
    slug: makeSlug("Gravity"),
    category: "FRUITS",
    rarity: "Mythical" as Rarity,
    imageUrl: "https://i.postimg.cc/D02Lw6vJ/Gravity.png",
    currentTradingValue: 10000000,
    permanentValue: 4680000000,
    demand: "5/10",
    demandScore: 5,
    trend: "Stable" as Trend,
    robuxPrice: 2300,
    beliPrice: 2500000
  },
  {
    id: "real-12",
    name: "Mammoth",
    slug: makeSlug("Mammoth"),
    category: "FRUITS",
    rarity: "Mythical" as Rarity,
    imageUrl: "https://i.postimg.cc/sXJGqWYV/Mammoth.png",
    currentTradingValue: 10000000,
    permanentValue: 4830000000,
    demand: "5/10",
    demandScore: 5,
    trend: "Stable" as Trend,
    robuxPrice: 2350,
    beliPrice: 2700000
  },
  {
    id: "real-13",
    name: "Spirit",
    slug: makeSlug("Spirit"),
    category: "FRUITS",
    rarity: "Mythical" as Rarity,
    imageUrl: "https://i.postimg.cc/wTpbhYvL/Spirit.png",
    currentTradingValue: 10000000,
    permanentValue: 5280000000,
    demand: "7/10",
    demandScore: 7,
    trend: "Stable" as Trend,
    robuxPrice: 2550,
    beliPrice: 3400000
  },
  {
    id: "real-14",
    name: "Venom",
    slug: makeSlug("Venom"),
    category: "FRUITS",
    rarity: "Mythical" as Rarity,
    imageUrl: "https://i.postimg.cc/zGdtZLkF/Venom.png",
    currentTradingValue: 20000000,
    permanentValue: 4830000000,
    demand: "8/10",
    demandScore: 8,
    trend: "Stable" as Trend,
    robuxPrice: 2450,
    beliPrice: 3000000
  },
  {
    id: "real-15",
    name: "Shadow",
    slug: makeSlug("Shadow"),
    category: "FRUITS",
    rarity: "Mythical" as Rarity,
    imageUrl: "https://i.postimg.cc/kGpGPvBd/Shadow.png",
    currentTradingValue: 6500000,
    permanentValue: 4830000000,
    demand: "5/10",
    demandScore: 5,
    trend: "Stable" as Trend,
    robuxPrice: 2425,
    beliPrice: 2900000
  },
  {
    id: "real-16",
    name: "Portal",
    slug: makeSlug("Portal"),
    category: "FRUITS",
    rarity: "Legendary" as Rarity,
    imageUrl: "https://i.postimg.cc/DzkWz65v/Portal.png",
    currentTradingValue: 10000000,
    permanentValue: 3870000000,
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 2000,
    beliPrice: 1900000
  },
  {
    id: "real-17",
    name: "Buddha",
    slug: makeSlug("Buddha"),
    category: "FRUITS",
    rarity: "Legendary" as Rarity,
    imageUrl: "https://i.postimg.cc/02nZD6h1/Buddha.png",
    currentTradingValue: 10000000,
    permanentValue: 3090000000,
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 1650,
    beliPrice: 1200000
  },
  {
    id: "real-18",
    name: "Blizzard",
    slug: makeSlug("Blizzard"),
    category: "FRUITS",
    rarity: "Legendary" as Rarity,
    imageUrl: "https://i.postimg.cc/fTDBV72v/Blizzard.png",
    currentTradingValue: 5000000,
    permanentValue: 4410000000,
    demand: "5/10",
    demandScore: 5,
    trend: "Stable" as Trend,
    robuxPrice: 2250,
    beliPrice: 2400000
  },
  {
    id: "real-19",
    name: "Creation",
    slug: makeSlug("Creation"),
    category: "FRUITS",
    rarity: "Legendary" as Rarity,
    imageUrl: "https://i.postimg.cc/HLctq6nT/Creation.png",
    currentTradingValue: 3000000,
    permanentValue: 3210000000,
    demand: "2/10",
    demandScore: 2,
    trend: "Stable" as Trend,
    robuxPrice: 1750,
    beliPrice: 1400000
  },
  {
    id: "real-20",
    name: "Phoenix",
    slug: makeSlug("Phoenix"),
    category: "FRUITS",
    rarity: "Legendary" as Rarity,
    imageUrl: "https://i.postimg.cc/DwbJFHrp/Phoenix.png",
    currentTradingValue: 2750000,
    permanentValue: 3870000000,
    demand: "3/10",
    demandScore: 3,
    trend: "Stable" as Trend,
    robuxPrice: 2000,
    beliPrice: 1800000
  },
  {
    id: "real-21",
    name: "Sound",
    slug: makeSlug("Sound"),
    category: "FRUITS",
    rarity: "Legendary" as Rarity,
    imageUrl: "https://i.postimg.cc/MKgHs5C7/Sound.png",
    currentTradingValue: 2500000,
    permanentValue: 3540000000,
    demand: "4/10",
    demandScore: 4,
    trend: "Stable" as Trend,
    robuxPrice: 1900,
    beliPrice: 1700000
  },
  {
    id: "real-22",
    name: "Spider",
    slug: makeSlug("Spider"),
    category: "FRUITS",
    rarity: "Legendary" as Rarity,
    imageUrl: "https://i.postimg.cc/MpRTgRwh/Spider.png",
    currentTradingValue: 1500000,
    permanentValue: 3330000000,
    demand: "2/10",
    demandScore: 2,
    trend: "Stable" as Trend,
    robuxPrice: 1800,
    beliPrice: 1500000
  },
  {
    id: "real-23",
    name: "Love",
    slug: makeSlug("Love"),
    category: "FRUITS",
    rarity: "Legendary" as Rarity,
    imageUrl: "https://i.postimg.cc/0NDwGFrK/Love.png",
    currentTradingValue: 1500000,
    permanentValue: 3090000000,
    demand: "3/10",
    demandScore: 3,
    trend: "Stable" as Trend,
    robuxPrice: 1700,
    beliPrice: 1300000
  },
  {
    id: "real-24",
    name: "Magma",
    slug: makeSlug("Magma"),
    category: "FRUITS",
    rarity: "Rare" as Rarity,
    imageUrl: "https://i.postimg.cc/W3VJ58JW/Magma.png",
    currentTradingValue: 1150000,
    permanentValue: 2070000000,
    demand: "5/10",
    demandScore: 5,
    trend: "Overpaid" as Trend,
    robuxPrice: 1300,
    beliPrice: 960000
  },
  {
    id: "real-25",
    name: "Quake",
    slug: makeSlug("Quake"),
    category: "FRUITS",
    rarity: "Legendary" as Rarity,
    imageUrl: "https://i.postimg.cc/cJRvt35Q/Quake.png",
    currentTradingValue: 1000000,
    permanentValue: 2670000000,
    demand: "2/10",
    demandScore: 2,
    trend: "Stable" as Trend,
    robuxPrice: 1500,
    beliPrice: 1000000
  },
  {
    id: "real-26",
    name: "Diamond",
    slug: makeSlug("Diamond"),
    category: "FRUITS",
    rarity: "Uncommon" as Rarity,
    imageUrl: "https://i.postimg.cc/3N7CD7Bw/Diamond.png",
    currentTradingValue: 1000000,
    permanentValue: 1170000000,
    demand: "2/10",
    demandScore: 2,
    trend: "Stable" as Trend,
    robuxPrice: 1000,
    beliPrice: 600000
  },
  {
    id: "real-27",
    name: "Light",
    slug: makeSlug("Light"),
    category: "FRUITS",
    rarity: "Rare" as Rarity,
    imageUrl: "https://i.postimg.cc/K8dTMxcy/Light.png",
    currentTradingValue: 800000,
    permanentValue: 1650000000,
    demand: "2/10",
    demandScore: 2,
    trend: "Stable" as Trend,
    robuxPrice: 1100,
    beliPrice: 650000
  },
  {
    id: "real-28",
    name: "Ghost",
    slug: makeSlug("Ghost"),
    category: "FRUITS",
    rarity: "Rare" as Rarity,
    imageUrl: "https://i.postimg.cc/k4PWk9Ly/Ghost.png",
    currentTradingValue: 800000,
    permanentValue: 1920000000,
    demand: "1/10",
    demandScore: 1,
    trend: "Underpaid" as Trend,
    robuxPrice: 1275,
    beliPrice: 940000
  },
  {
    id: "real-29",
    name: "Eagle",
    slug: makeSlug("Eagle"),
    category: "FRUITS",
    rarity: "Uncommon" as Rarity,
    imageUrl: "https://i.postimg.cc/sxcPY864/Eagle.png",
    currentTradingValue: 800000,
    permanentValue: 1110000000,
    demand: "2/10",
    demandScore: 2,
    trend: "Stable" as Trend,
    robuxPrice: 975,
    beliPrice: 550000
  },
  {
    id: "real-30",
    name: "Rubber",
    slug: makeSlug("Rubber"),
    category: "FRUITS",
    rarity: "Rare" as Rarity,
    imageUrl: "https://i.postimg.cc/qRQgjTrq/Rubber.png",
    currentTradingValue: 700000,
    permanentValue: 1770000000,
    demand: "1/10",
    demandScore: 1,
    trend: "Stable" as Trend,
    robuxPrice: 1200,
    beliPrice: 750000
  },
  {
    id: "real-31",
    name: "Ice",
    slug: makeSlug("Ice"),
    category: "FRUITS",
    rarity: "Uncommon" as Rarity,
    imageUrl: "https://i.postimg.cc/zDjTPs7n/Ice.png",
    currentTradingValue: 550000,
    permanentValue: 630000000,
    demand: "2/10",
    demandScore: 2,
    trend: "Stable" as Trend,
    robuxPrice: 750,
    beliPrice: 350000
  },
  {
    id: "real-32",
    name: "Sand",
    slug: makeSlug("Sand"),
    category: "FRUITS",
    rarity: "Uncommon" as Rarity,
    imageUrl: "https://i.postimg.cc/QxFVkwyN/Sand.png",
    currentTradingValue: 420000,
    permanentValue: 840000000,
    demand: "1/10",
    demandScore: 1,
    trend: "Stable" as Trend,
    robuxPrice: 850,
    beliPrice: 420000
  },
  {
    id: "real-33",
    name: "Dark",
    slug: makeSlug("Dark"),
    category: "FRUITS",
    rarity: "Uncommon" as Rarity,
    imageUrl: "https://i.postimg.cc/0NTCP7KD/Dark.png",
    currentTradingValue: 400000,
    permanentValue: 1050000000,
    demand: "1/10",
    demandScore: 1,
    trend: "Stable" as Trend,
    robuxPrice: 950,
    beliPrice: 500000
  },
  {
    id: "real-34",
    name: "Flame",
    slug: makeSlug("Flame"),
    category: "FRUITS",
    rarity: "Uncommon" as Rarity,
    imageUrl: "https://i.postimg.cc/y8WhRLF0/Flame.png",
    currentTradingValue: 250000,
    permanentValue: 450000000,
    demand: "1/10",
    demandScore: 1,
    trend: "Stable" as Trend,
    robuxPrice: 550,
    beliPrice: 250000
  },
  {
    id: "real-35",
    name: "Spike",
    slug: makeSlug("Spike"),
    category: "FRUITS",
    rarity: "Common" as Rarity,
    imageUrl: "https://i.postimg.cc/fbNLsLTk/Spike.png",
    currentTradingValue: 180000,
    permanentValue: 140000000,
    demand: "1/10",
    demandScore: 1,
    trend: "Stable" as Trend,
    robuxPrice: 380,
    beliPrice: 180000
  },
  {
    id: "real-36",
    name: "Smoke",
    slug: makeSlug("Smoke"),
    category: "FRUITS",
    rarity: "Common" as Rarity,
    imageUrl: "https://i.postimg.cc/nVRCmpTw/Smoke.png",
    currentTradingValue: 100000,
    permanentValue: 120000000,
    demand: "1/10",
    demandScore: 1,
    trend: "Stable" as Trend,
    robuxPrice: 250,
    beliPrice: 100000
  },
  {
    id: "real-37",
    name: "Bomb",
    slug: makeSlug("Bomb"),
    category: "FRUITS",
    rarity: "Common" as Rarity,
    imageUrl: "https://i.postimg.cc/y8NjP1zg/Bomb.png",
    currentTradingValue: 80000,
    permanentValue: 90000000,
    demand: "1/10",
    demandScore: 1,
    trend: "Stable" as Trend,
    robuxPrice: 220,
    beliPrice: 80000
  },
  {
    id: "real-38",
    name: "Spring",
    slug: makeSlug("Spring"),
    category: "FRUITS",
    rarity: "Common" as Rarity,
    imageUrl: "https://i.postimg.cc/15r7B7nT/Spring.png",
    currentTradingValue: 60000,
    permanentValue: 60000000,
    demand: "1/10",
    demandScore: 1,
    trend: "Stable" as Trend,
    robuxPrice: 180,
    beliPrice: 60000
  },
  {
    id: "real-39",
    name: "Blade",
    slug: makeSlug("Blade"),
    category: "SWORDS",
    rarity: "Common" as Rarity,
    imageUrl: "https://i.postimg.cc/bYQmYVTJ/Blade.png",
    currentTradingValue: 50000,
    permanentValue: 20000000,
    demand: "1/10",
    demandScore: 1,
    trend: "Stable" as Trend,
    robuxPrice: 100,
    beliPrice: 30000
  },
  {
    id: "real-40",
    name: "Spin",
    slug: makeSlug("Spin"),
    category: "FRUITS",
    rarity: "Common" as Rarity,
    imageUrl: "https://i.postimg.cc/jj4jSbLc/Spin.png",
    currentTradingValue: 7500,
    permanentValue: 15000000,
    demand: "1/10",
    demandScore: 1,
    trend: "Stable" as Trend,
    robuxPrice: 75,
    beliPrice: 7500
  },
  {
    id: "real-41",
    name: "Rocket",
    slug: makeSlug("Rocket"),
    category: "FRUITS",
    rarity: "Common" as Rarity,
    imageUrl: "https://i.postimg.cc/cHdrRJVP/Rocket.png",
    currentTradingValue: 5000,
    permanentValue: 10000000,
    demand: "1/10",
    demandScore: 1,
    trend: "Stable" as Trend,
    robuxPrice: 50,
    beliPrice: 5000
  },
  {
    id: "real-42",
    name: "Permanent Dragon Token",
    slug: makeSlug("Permanent Dragon Token"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/59nFmw9g/Permanent-Dragon-Token.png",
    currentTradingValue: 0,
    
    demand: "6/10",
    demandScore: 6,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-43",
    name: "Fiend Yeti",
    slug: makeSlug("Fiend Yeti"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/fbBmGbCv/latest-cb-20260214132352.webp",
    currentTradingValue: 1110000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-44",
    name: "Galaxy Empyrean Kitsune",
    slug: makeSlug("Galaxy Empyrean Kitsune"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/k5JRY7vf/latest-cb-20251226164613.webp",
    currentTradingValue: 14580000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-45",
    name: "Ember West Dragon",
    slug: makeSlug("Ember West Dragon"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/Qtn7Wv59/latest-cb-20251226164628.webp",
    currentTradingValue: 8520000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-46",
    name: "Crimson Kitsune",
    slug: makeSlug("Crimson Kitsune"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/dtg9fZh5/latest-cb-20251225145618.webp",
    currentTradingValue: 11790000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 2000,
    beliPrice: 0
  },
  {
    id: "real-47",
    name: "Meme-Meme",
    slug: makeSlug("Meme-Meme"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/KYLd2W5J/latest-cb-20260402183037.webp",
    currentTradingValue: 7290000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-48",
    name: "Divine Portal",
    slug: makeSlug("Divine Portal"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/htF9sFwc/latest-cb-20251225222313.webp",
    currentTradingValue: 2040000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-49",
    name: "Purple Lightning",
    slug: makeSlug("Purple Lightning"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/d0FsYGYD/Purple-Lightning.png",
    currentTradingValue: 7170000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-50",
    name: "Parrot",
    slug: makeSlug("Parrot"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/dt3ZNLLY/Parrot.png",
    currentTradingValue: 0,
    
    demand: "1/10",
    demandScore: 1,
    trend: "Stable" as Trend,
    robuxPrice: 499,
    beliPrice: 0
  },
  {
    id: "real-51",
    name: "Red Lightning",
    slug: makeSlug("Red Lightning"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/s2DmjTkH/Red-Lightning.png",
    currentTradingValue: 2310000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-52",
    name: "Yellow Lightning",
    slug: makeSlug("Yellow Lightning"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/cLwx2XPV/Yellow-Lightning.png",
    currentTradingValue: 2340000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-53",
    name: "Green Lightning",
    slug: makeSlug("Green Lightning"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/MKcKbW5Z/Green-Lightning.png",
    currentTradingValue: 720000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-54",
    name: "Werewolf",
    slug: makeSlug("Werewolf"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/mr2jLmv5/Werewolf.png",
    currentTradingValue: 1200000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-55",
    name: "Rose Quartz Diamond",
    slug: makeSlug("Rose Quartz Diamond"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/02PQqRHR/Rose-Quartz.webp",
    currentTradingValue: 280000000,
    
    demand: "7/10",
    demandScore: 7,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-56",
    name: "Emerald Diamond",
    slug: makeSlug("Emerald Diamond"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/8zCzjdSZ/Emerald.webp",
    currentTradingValue: 220000000,
    
    demand: "6/10",
    demandScore: 6,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-57",
    name: "Topaz Diamond",
    slug: makeSlug("Topaz Diamond"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/VLgNfG3S/Topaz.webp",
    currentTradingValue: 220000000,
    
    demand: "6/10",
    demandScore: 6,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-58",
    name: "Ruby Diamond",
    slug: makeSlug("Ruby Diamond"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/9XGMSFbY/Ruby.webp",
    currentTradingValue: 170000000,
    
    demand: "6/10",
    demandScore: 6,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-59",
    name: "Dragon Token",
    slug: makeSlug("Dragon Token"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/hPYzkcd7/Dragon-Token.png",
    currentTradingValue: 0,
    
    demand: "4/10",
    demandScore: 4,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-60",
    name: "Eclipse",
    slug: makeSlug("Eclipse"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/65MLTkG9/Eclipse.png",
    currentTradingValue: 0,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-61",
    name: "Super Spirit Pain",
    slug: makeSlug("Super Spirit Pain"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/Xv7LjsRD/Super-Spirit-Pain.png",
    currentTradingValue: 2280000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-62",
    name: "Torment Pain",
    slug: makeSlug("Torment Pain"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/T1qGN3Q0/Torment.png",
    currentTradingValue: 140000000,
    
    demand: "7/10",
    demandScore: 7,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-63",
    name: "Sadness Pain",
    slug: makeSlug("Sadness Pain"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/C5VS4qCd/Sadness.png",
    currentTradingValue: 720000000,
    
    demand: "9/10",
    demandScore: 9,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-64",
    name: "Frustration Pain",
    slug: makeSlug("Frustration Pain"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/26WCvwZP/Frustration.png",
    currentTradingValue: 510000000,
    
    demand: "9/10",
    demandScore: 9,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-65",
    name: "Celestial Pain",
    slug: makeSlug("Celestial Pain"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/RC7ZvC2r/Celestial-Pain.png",
    currentTradingValue: 720000000,
    
    demand: "9/10",
    demandScore: 9,
    trend: "Overpaid" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-66",
    name: "Eagle Requiem",
    slug: makeSlug("Eagle Requiem"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/7P3ZqPjr/Eagle-Requiem.png",
    currentTradingValue: 160000000,
    
    demand: "4/10",
    demandScore: 4,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-67",
    name: "Eagle Glacier",
    slug: makeSlug("Eagle Glacier"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/qBsvpBWV/Eagle-Glacier.png",
    currentTradingValue: 20000000,
    
    demand: "3/10",
    demandScore: 3,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-68",
    name: "Eagle Matrix",
    slug: makeSlug("Eagle Matrix"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/446xX4qD/Eagle-Matrix.png",
    currentTradingValue: 250000000,
    
    demand: "7/10",
    demandScore: 7,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-69",
    name: "Celebration Bomb",
    slug: makeSlug("Celebration Bomb"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/Jh4xrpf6/Celebration-Bomb.png",
    currentTradingValue: 10000000,
    
    demand: "3/10",
    demandScore: 3,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-70",
    name: "Azura Bomb",
    slug: makeSlug("Azura Bomb"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/PfW5df9K/Azura-Bomb.png",
    currentTradingValue: 450000000,
    
    demand: "6/10",
    demandScore: 6,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-71",
    name: "Thermite Bomb",
    slug: makeSlug("Thermite Bomb"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/T2V3T2Bf/Thermite-Bomb.png",
    currentTradingValue: 450000000,
    
    demand: "6/10",
    demandScore: 6,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-72",
    name: "Nuclear Bomb",
    slug: makeSlug("Nuclear Bomb"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/QNQdjNvs/Nuclear-Bomb.png",
    currentTradingValue: 450000000,
    
    demand: "6/10",
    demandScore: 6,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-73",
    name: "Orange Portal",
    slug: makeSlug("Orange Portal"),
    category: "LIMITEDS",
    rarity: "Limited" as Rarity,
    imageUrl: "https://i.postimg.cc/RhvjdZB9/placeholder.png",
    currentTradingValue: 0,
    
    demand: "5/10",
    demandScore: 5,
    trend: "Stable" as Trend,
    robuxPrice: 0,
    beliPrice: 0
  },
  {
    id: "real-74",
    name: "Fruit Notifier",
    slug: makeSlug("Fruit Notifier"),
    category: "GAMEPASSES",
    rarity: "Gamepass" as Rarity,
    imageUrl: "https://i.postimg.cc/Zqdr70sR/Fruit-Notifer.png",
    currentTradingValue: 7170000000,
    
    demand: "9/10",
    demandScore: 9,
    trend: "Stable" as Trend,
    robuxPrice: 2700,
    beliPrice: 0
  },
  {
    id: "real-75",
    name: "Dark Blade",
    slug: makeSlug("Dark Blade"),
    category: "SWORDS",
    rarity: "Gamepass" as Rarity,
    imageUrl: "https://i.postimg.cc/fLYfLkYF/Dark-Blade.png",
    currentTradingValue: 1770000000,
    
    demand: "9/10",
    demandScore: 9,
    trend: "Stable" as Trend,
    robuxPrice: 1200,
    beliPrice: 0
  },
  {
    id: "real-76",
    name: "Mythical Scrolls",
    slug: makeSlug("Mythical Scrolls"),
    category: "SCROLLS",
    rarity: "Gamepass" as Rarity,
    imageUrl: "https://i.postimg.cc/d3HktKNp/Mythical-Scrolls.png",
    currentTradingValue: 2670000000,
    
    demand: "4/10",
    demandScore: 4,
    trend: "Stable" as Trend,
    robuxPrice: 1500,
    beliPrice: 0
  },
  {
    id: "real-77",
    name: "Legendary Scrolls",
    slug: makeSlug("Legendary Scrolls"),
    category: "SCROLLS",
    rarity: "Gamepass" as Rarity,
    imageUrl: "https://i.postimg.cc/YqDYtQJ0/Legendary-Scrolls.png",
    currentTradingValue: 810000000,
    
    demand: "3/10",
    demandScore: 3,
    trend: "Stable" as Trend,
    robuxPrice: 800,
    beliPrice: 0
  },
  {
    id: "real-78",
    name: "+1 Fruit Storage",
    slug: makeSlug("+1 Fruit Storage"),
    category: "GAMEPASSES",
    rarity: "Gamepass" as Rarity,
    imageUrl: "https://i.postimg.cc/hj7pmcdF/1-Fruit-Storage.png",
    currentTradingValue: 450000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 400,
    beliPrice: 0
  },
  {
    id: "real-79",
    name: "2x Mastery",
    slug: makeSlug("2x Mastery"),
    category: "GAMEPASSES",
    rarity: "Gamepass" as Rarity,
    imageUrl: "https://i.postimg.cc/0jdntrQm/2x-Mastery.png",
    currentTradingValue: 450000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 450,
    beliPrice: 0
  },
  {
    id: "real-80",
    name: "2x Money",
    slug: makeSlug("2x Money"),
    category: "GAMEPASSES",
    rarity: "Gamepass" as Rarity,
    imageUrl: "https://i.postimg.cc/rsLgC58M/2x-Money.png",
    currentTradingValue: 450000000,
    
    demand: "10/10",
    demandScore: 10,
    trend: "Overpaid" as Trend,
    robuxPrice: 450,
    beliPrice: 0
  },
  {
    id: "real-81",
    name: "2x Boss Drops",
    slug: makeSlug("2x Boss Drops"),
    category: "GAMEPASSES",
    rarity: "Gamepass" as Rarity,
    imageUrl: "https://i.postimg.cc/HxMBy616/2x-Boss-Drops.png",
    currentTradingValue: 300000000,
    
    demand: "8/10",
    demandScore: 8,
    trend: "Overpaid" as Trend,
    robuxPrice: 350,
    beliPrice: 0
  },
  {
    id: "real-82",
    name: "Fast Boats",
    slug: makeSlug("Fast Boats"),
    category: "GAMEPASSES",
    rarity: "Gamepass" as Rarity,
    imageUrl: "https://i.postimg.cc/NjV6kR4S/Fast-Boats.png",
    currentTradingValue: 300000000,
    
    demand: "9/10",
    demandScore: 9,
    trend: "Overpaid" as Trend,
    robuxPrice: 350,
    beliPrice: 0
  },
];
